# -*- coding: utf-8 -*-
"""Dashboard Streamlit_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17xmIWuWWYakg933HFbAHwkmVd1QzLMxr
"""

import streamlit as st
import pandas as pd
import numpy as np
import plotly.graph_objects as go
from datetime import time

st.set_page_config(
    page_title="Solar GHI Forecasting Dashboard",
    layout="wide"
)

st.markdown(
    "<h1 style='text-align: center;'>☀️ Solar GHI Forecasting Dashboard</h1>",
    unsafe_allow_html=True
)

DATA_PATH = "Bias Correction_with_Day_Ahead_Forecast.csv"

@st.cache_data
def load_data():
    df = pd.read_csv(DATA_PATH)

    df["valid_time_ist"] = pd.to_datetime(df["valid_time_ist"])

    df = df.rename(columns={
        "avg_ghi": "GFS_GHI",
        "ALLSKY_SFC_SW_DWN": "Actual_GHI",
        "Day_Ahead_Forecast": "Daily_Forecast_GHI"
    })

    df = df.sort_values("valid_time_ist").reset_index(drop=True)
    return df

df = load_data()

st.subheader("🏭 Plant & Forecast Configuration")

available_dates = sorted(df["valid_time_ist"].dt.date.unique())

c1, c2, c3, c4 = st.columns([1, 1.5, 1, 1])

with c1:
    state = st.selectbox(
        "State",
        ["Karnataka"]
    )

with c2:
    plant = st.selectbox(
        "Plant Name",
        ["Pavagada Solar Plant"]
    )

with c3:
    selected_date = st.date_input(
        "Date",
        value=available_dates[-1],
        min_value=available_dates[0],
        max_value=available_dates[-1]
    )

with c4:
    time_options = pd.date_range("06:30", "17:30", freq="1h").time

    selected_time = st.selectbox(
        "Time",
        options=time_options,
        format_func=lambda t: t.strftime("%I:%M %p")
    )


day_df = df[df["valid_time_ist"].dt.date == selected_date].copy()

day_df["hour"] = (
    day_df["valid_time_ist"].dt.hour +
    day_df["valid_time_ist"].dt.minute / 60
)

day_df = day_df[
    (day_df["hour"] >= 6.5) &
    (day_df["hour"] <= 17.5)
].copy()

if day_df.empty:
    st.warning("No data available for the selected date.")

else:
    st.success(f"Prediction available for {selected_date}")

    left_col, right_col = st.columns(2)

    ymax = max(
        day_df["Actual_GHI"].max(),
        day_df["GFS_GHI"].max(),
        day_df["Daily_Forecast_GHI"].max()
    )

    ymax = (int(ymax / 100) + 1) * 100

    tick_times = day_df["valid_time_ist"].dt.strftime("%H:%M").tolist()

    # =====================================================
    # FIRST ROW: DAILY FORECAST GHI ONLY
    # =====================================================

    fig1 = go.Figure()

    fig1.add_trace(go.Scatter(
        x=day_df["valid_time_ist"],
        y=day_df["Daily_Forecast_GHI"],
        mode="lines+markers",
        name="Daily Forecast GHI",
        line=dict(color="red"),
        marker=dict(color="red")
    ))

    fig1.update_layout(
        title="Daily Forecast GHI",
        xaxis_title="Time",
        yaxis_title="GHI",
        height=450,
        legend=dict(
            orientation="h",
            yanchor="bottom",
            y=1.02,
            xanchor="right",
            x=1
        )
    )

    fig1.update_xaxes(
        tickmode="array",
        tickvals=day_df["valid_time_ist"],
        ticktext=tick_times
    )

    fig1.update_yaxes(range=[0, ymax])

    row1_col, row1_space = st.columns([4.5, 0.8])

    with row1_col:
        st.plotly_chart(fig1, use_container_width=True, key="daily_forecast_main")
    # =====================================================
    # SECOND ROW: TWO PLOTS
    # LEFT: GFS VS DAILY FORECAST
    # RIGHT: DAILY FORECAST GHI ONLY
    # =====================================================

    left_col, right_col = st.columns(2)

    with left_col:
        fig2 = go.Figure()

        fig2.add_trace(go.Scatter(
            x=day_df["valid_time_ist"],
            y=day_df["GFS_GHI"],
            mode="lines+markers",
            name="GFS GHI"
        ))

        fig2.add_trace(go.Scatter(
            x=day_df["valid_time_ist"],
            y=day_df["Daily_Forecast_GHI"],
            mode="lines+markers",
            name="Daily Forecast GHI",
            line=dict(color="red"),
            marker=dict(color="red")
        ))

        fig2.update_layout(
            title="GFS vs Daily Forecast GHI",
            xaxis_title="Time",
            yaxis_title="GHI",
            height=450,
            legend=dict(
                orientation="h",
                yanchor="bottom",
                y=1.02,
                xanchor="right",
                x=1
            )
        )

        fig2.update_xaxes(
            tickmode="array",
            tickvals=day_df["valid_time_ist"],
            ticktext=tick_times
        )

        fig2.update_yaxes(range=[0, ymax])

        st.plotly_chart(fig2, use_container_width=True, key="gfs_vs_daily_forecast")

    with right_col:
        fig3 = go.Figure()

        fig3.add_trace(go.Scatter(
            x=day_df["valid_time_ist"],
            y=day_df["Daily_Forecast_GHI"],
            mode="lines+markers",
            name="Daily Forecast GHI",
            line=dict(color="red"),
            marker=dict(color="red")
          
        ))

        fig3.update_layout(
            title="Daily Forecast GHI",
            xaxis_title="Time",
            yaxis_title="GHI",
            height=450,
            legend=dict(
                orientation="h",
                yanchor="bottom",
                y=1.02,
                xanchor="right",
                x=1
            )
        )

        fig3.update_xaxes(
            tickmode="array",
            tickvals=day_df["valid_time_ist"],
            ticktext=tick_times
        )

        fig3.update_yaxes(range=[0, ymax])

        st.plotly_chart(fig3, use_container_width=True, key="daily_forecast_side")


    # =====================================================
    # CUMULATIVE ERROR METRICS: START DATE TO PREVIOUS DAY
    # =====================================================

    selected_date_only = pd.to_datetime(selected_date).date()
    previous_day = selected_date_only - pd.Timedelta(days=1)

    eval_df = df[
        df["valid_time_ist"].dt.date <= previous_day
    ].copy()

    eval_df = eval_df.dropna(
        subset=["Actual_GHI", "GFS_GHI", "Daily_Forecast_GHI"]
    )

    eval_df["hour"] = (
        eval_df["valid_time_ist"].dt.hour +
        eval_df["valid_time_ist"].dt.minute / 60
    )

    eval_df = eval_df[
        (eval_df["hour"] >= 6.5) &
        (eval_df["hour"] <= 17.5) &
        (eval_df["Actual_GHI"] > 50)
    ].copy()

    if not eval_df.empty:

        start_date = eval_df["valid_time_ist"].dt.date.min()
        end_date = eval_df["valid_time_ist"].dt.date.max()

        actual = eval_df["Actual_GHI"]
        before = eval_df["GFS_GHI"]
        after = eval_df["Daily_Forecast_GHI"]

        mae_before = (actual - before).abs().mean()
        mae_after = (actual - after).abs().mean()

        rmse_before = np.sqrt(((actual - before) ** 2).mean())
        rmse_after = np.sqrt(((actual - after) ** 2).mean())

        mape_before = ((actual - before).abs() / actual).mean() * 100
        mape_after = ((actual - after).abs() / actual).mean() * 100

        st.markdown(
            f"### 📊 Cumulative Forecast Performance "
            f"({start_date} to {end_date})"
        )

        metric_col1, metric_col2, metric_col3 = st.columns(3)

        # ---------------- MAPE ----------------
        with metric_col1:
            fig_mape = go.Figure()

            fig_mape.add_trace(go.Bar(
                x=["Before", "After"],
                y=[mape_before, mape_after],
                text=[round(mape_before, 2), round(mape_after, 2)],
                textposition="auto",
                marker_color=["steelblue", "red"]
            ))

            fig_mape.update_layout(
                title="MAPE",
                xaxis_title="Model",
                yaxis_title="MAPE (%)",
                height=350
            )

            st.plotly_chart(
                fig_mape,
                use_container_width=True,
                key="mape_cumulative_chart"
            )

        # ---------------- MAE ----------------
        with metric_col2:
            fig_mae = go.Figure()

            fig_mae.add_trace(go.Bar(
                x=["Before", "After"],
                y=[mae_before, mae_after],
                text=[round(mae_before, 2), round(mae_after, 2)],
                textposition="auto",
                marker_color=["steelblue", "red"]
            ))

            fig_mae.update_layout(
                title="MAE",
                xaxis_title="Model",
                yaxis_title="MAE",
                height=350
            )

            st.plotly_chart(
                fig_mae,
                use_container_width=True,
                key="mae_cumulative_chart"
            )

        # ---------------- RMSE ----------------
        with metric_col3:
            fig_rmse = go.Figure()

            fig_rmse.add_trace(go.Bar(
                x=["Before", "After"],
                y=[rmse_before, rmse_after],
                text=[round(rmse_before, 2), round(rmse_after, 2)],
                textposition="auto",
                marker_color=["steelblue", "red"]
            ))

            fig_rmse.update_layout(
                title="RMSE",
                xaxis_title="Model",
                yaxis_title="RMSE",
                height=350
            )

            st.plotly_chart(
                fig_rmse,
                use_container_width=True,
                key="rmse_cumulative_chart"
            )

    else:
        st.warning(
            "Not enough valid previous-day data to calculate cumulative forecast performance."
        )
